### PR TITLE
Make 'kitchen-docker' work in OSX.

### PR DESCRIPTION
**Pull request by jvrplmlmn**
Reference:
- https://github.com/test-kitchen/kitchen-docker/issues/207
- https://github.com/test-kitchen/kitchen-docker/issues/201

Solves:

image

WDYT @armab ?

### CODE REVIEW

**Comment by armab** [comment]
Seems like CI is unhappy with `use_sudo: false`.

**Comment by armab** [comment]
Update: Nope, I re-ran build for `master` and it failed too.
Probably some software was updated, let me check.

**Comment by armab** [comment]
Fixed upstream failures in `master` https://github.com/StackStorm/ansible-st2/pull/55.

You can sync-up (rebase on top of master) and let's see CI status once again.

**Comment by jvrplmlmn** [comment]
Weird, after rebasing, it worked locally, but seems to have failed in Travis. I'll do empty-commit + rebase/squash to trigger Travis again.

**Comment by jvrplmlmn** [comment]
@armab good to go 👍

**Comment by armab** [comment]
Thanks!

**Pull request merged**
