### PR TITLE
Small changes [RFR]

### PR DESCRIPTION
**Pull request by armab**
* [x] Check for minimum requirements like `memory`
* [x] Version check before install (check if `13.5.99` version is available)
* [x] `stable`, `unstable` support (besides of numeric `0.12.1` version)
* [x] Vagrantfile
* [ ] ~~Tag all tasks, split into logical groups~~ (next PR)
* [x] Refactor all variables, add `st2_` prefix (best practice for Ansible Galaxy)
* [x] Upgrade to higher st2 version as well as downgrade should work (it doesn't)
* [ ] ~~Add missing [PostgreSQL installation](https://github.com/StackStorm/st2/blob/b6b87aeb62c8301409b6b8fe16a6d4826560ff4f/tools/st2_deploy.sh#L280) for Mistral~~ (next PR)
* [x] Fix Upstart
* [x] Upstart `N` action-runners
* [ ] ~~Further verify/sync existing logic with [`st2_deploy.sh`](https://github.com/StackStorm/st2/blob/master/tools/st2_deploy.sh)~~ (next PR)
* [x] Initial Docs 

Part of #2

### CODE REVIEW

**Comment by armab** [comment]
@jfryman @enykeev This PR is ready for review/merging.

Initial docs: https://github.com/armab/ansible-st2/blob/small-fixes/README.md

**Comment by jfryman** [comment]
Did this get pushed to Ansible Galaxy, or is that after some more improvements?

**Comment by armab** [comment]
Yeah, it's still far away to be ready for Ansible Galaxy.

I need to remove existing roles (MySQL, Mongo, RabbitMQ, PostgreSQL), instead of that reuse 3rd party Ansible Galaxy roles. As a result there will be only `st2` role with dependencies.
Many more improvements/fixes from [that checklist](https://github.com/StackStorm/ansible-st2/issues/2) needed, including ci/tests to make it good enough for Galaxy.

Here are just minimal changes which I'm sure won't change during time, like renamed variable names. I'm moving to that point (Ansible Galaxy and Stability) in small steps.

**Comment by jfryman** [comment]
@armab good deal. Thanks for the info. I assumed as much, but you know what happens when one assumes. :grin:

**Comment by armab** [comment]
No problem with that.
I should provide more clear descriptions.

And we're on the same wave about Ansible Galaxy idea :+1:

**Pull request merged**
