### PR TITLE
Install gpg before calling apt_key

### LINKED ISSUE #304: Installation fails on Ubuntu Focal 20.04.3
Fresh installation of Focal (minimal) yields:

```bash
TASK [StackStorm.mongodb : apt | Add mongodb key] ********************************************************************************************
FAILED - RETRYING: [stackstorm]: apt | Add mongodb key (5 retries left).
FAILED - RETRYING: [stackstorm]: apt | Add mongodb key (4 retries left).
FAILED - RETRYING: [stackstorm]: apt | Add mongodb key (3 retries left).
FAILED - RETRYING: [stackstorm]: apt | Add mongodb key (2 retries left).
FAILED - RETRYING: [stackstorm]: apt | Add mongodb key (1 retries left).
fatal: [stackstorm]: FAILED! => {"attempts": 5, "changed": false, "msg": "Failed to find required executable \"gpg\" in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"}
```

### PR DESCRIPTION
**Pull request by mamercad**
Fixes #304 (at least the first problem).

### CODE REVIEW

**Comment by mamercad** [comment]
These two changes get me through the installation (on Focal, at least):

```bash
PLAY RECAP ******************************************************************************************************************
stackstorm                 : ok=86   changed=0    unreachable=0    failed=0    skipped=63   rescued=0    ignored=1
```

**Comment by mamercad** [comment]
I don't see how these changes could cause the failures that I'm seeing in the integration tests... I'll dig deeper when I get a chance.

**Comment by mamercad** [comment]
Hrm, I was able to `vagrant up ubuntu18` and `vagrant up ubuntu20` without issue, probably going to need some help understanding why the integrations tests are failing.

**Review by armab — APPROVED** [review]
Thanks for the PR! :+1: 

Everything looks good, just left one minor comment.

Looks like the failure is irrelevant to your PR as it breaks on the chatops tests.
We recently switched the CI system and looks like the GH Actions is not passing some chatops secret used in tests to the forked builds. We'll try to fix that in another PR.

**Comment by mamercad** [comment]
> Thanks for the PR! 👍
> 
> Everything looks good, just left one minor comment.
> 
> The failure is irrelevant to your PR as it breaks on the chatops tests. We recently switched the CI system and looks like the GH Actions is not passing some chatops secret used in tests to the forked builds. We'll try to fix that in another PR.

Sweet, thanks for the help; I was surely confused since things were working locally (with Vagrant).

**Pull request merged**
