### PR TITLE
Fix e2e tests, drop Ubuntu18

### PR DESCRIPTION
**Pull request by setswei**
Hey @armab 

I have found the issues with the ansible-st2 build process

1. There was an incompatibility with docker-py using the latest versions of the requests and urllib3 libraries. This caused issues with molecule talking to the docker API on the host machine. Installing the requests<=2.29.0 resolved this issue. More info located here -> https://github.com/docker/docker-py/issues/3113

2. After getting the build processes working again I found that Ubuntu 18.04 tests would fail. this is due to MongoDB allowing the apt key for MongoDB 4.0 to expire. From the looks of some of the forum posts on the MongoDB community, they are not going to fix this as Ubuntu 18.04 was EOL on May 31 2023. For now, I have removed Ubuntu 18.04 from the build process, to resolve the MongoDB installation issues the role would have to be modified to download the deb packages directly and then install them (which can easily be done) but the main question I would put forward is should ubuntu 18.04 continued to be supported when there will be no mainstream OS level patches and vendors are dropping support as well.

As you can see below the builds are now working (except for Ubuntu 18.04)
image

If you check my repository you will see subsequent builds that have been completed with ubuntu 18.04 excluded

### CODE REVIEW

**Comment by setswei** [comment]
image

Completed Unit Tests

**Review by armab — CHANGES_REQUESTED** [review]
As we're dropping Ubuntu18 in this PR, let's also remove mentions of Ubuntu18 in other places of this repo too.

See: https://github.com/search?q=repo%3AStackStorm%2Fansible-st2%20Ubuntu&type=code

More changes needed in the README, Ansible meta files, Vagrantfile, etc.

**Comment by setswei** [comment]
Hey @armab 

no problem I will remove all references to ubuntu18. I didn’t do this initially incase it was still going to be supported for a bit.

I will have the updates committed later today

**Comment by armab** [comment]
Makes sense. TBH, I'm still completely not sure if we want to remove it this way, but I guess folks using ansible-st2 could pin

**Comment by setswei** [comment]
I have made the changes that you asked for. Users who have already deployed the apt repos would still see errors when talking to the repository due to the expired keys. bypassing the certificates can be a classified as a security risk. We can put some additional notes in the readme about ubuntu 18.04 as this is a issue is not really related to ansible or stackstorm.

**Review by armab — CHANGES_REQUESTED** [review]
Thanks for the changes!

There are more meta files to update for every Ansible role that we have:  https://github.com/StackStorm/ansible-st2/blob/222ee03e66a842a9d47322662ba89f3d5457eab9/roles/StackStorm.st2/meta/main.yml#L9-L11

**Comment by setswei** [comment]
My apologies, ide search fail :P.

**Comment by setswei** [comment]
the roles meta files have been updated. Builds are running

**Review by armab — APPROVED** [review]
Something that was expected to be a fix became a deprecation of Ubuntu Bionic ;)

Thanks a lot for the contribution!

**Comment by setswei** [comment]
No problem at all. I will see if I can assist with some of the other builds too.

**Comment by armab** [comment]
Check `st2-docker` project failures, there might be some dependencies https://github.com/StackStorm/st2-docker/actions/runs/6568617107/job/17843305116#step:6:8 like `bats` to update. Relevant PR in another repo: https://github.com/StackStorm/stackstorm-k8s/pull/338

**Pull request merged**
