### PR TITLE
Add new 2.9 service: timersengine

### LINKED ISSUE #196: Add new service st2timersengine
https://github.com/StackStorm/st2docs/pull/749

StackStorm core is adding a new service `st2timersengine`. Need to add this to the service list: https://github.com/StackStorm/ansible-st2/blob/master/roles/st2/vars/main.yml#L5-L14

This way the service is enabled and started.

### PR DESCRIPTION
**Pull request by cognifloyd**
Add new 2.9 service: timersengine

Resolves #196

### CODE REVIEW

**Comment by cognifloyd** [comment]
I don't understand the test results. On systemd systems this passes, but the idempotence check fails on sysv/upstart because the st2workflowengine and st2timersengine both report changed every time they're requested to start.

**Comment by cognifloyd** [comment]
I'll drop the rest for now.

I'm surprised upgrading isn't supported as this is in the readme:
> st2_version | latest | StackStorm version to install. `present` to install available package, **`latest` to get automatic updates**, or pin it to numeric version like `2.2.0`.

So, installing st2 via ansible supports automatic updates but not upgrades?

**Comment by cognifloyd** [comment]
dropped upgrade logic and rebased on #200.

**Comment by armab** [comment]
That's a good and a valid question.

For Ansible I think we tend to follow slightly more simplified approach comparing to traditional Chef or Puppet ways.
It's a tradeoff we have to do balancing between complexity vs able to support it.
Apart of this migration scenarios there were more tough corner cases. If we add a few migrations today and don't support future migrations that would be not consistent.

I'll look at this PR in more detail later post 2.9 release. In a meantime, can you please create a new PR just for adding `st2timersengine` similar to https://github.com/StackStorm/ansible-st2/pull/198?

**Comment by cognifloyd** [comment]
I have a copy of the upgrade logic saved in a separate branch. This is now just the timersengine change.

**Pull request merged**
