### PR TITLE
Rename 'bwc' -> 'ewc' in role name and vars

### LINKED ISSUE #220: Rename BWC -> EWC
When reviewing the install steps for Enterprise components i notice that there are still references to BWC that should be renamed to EWC.

### PR DESCRIPTION
**Pull request by armab**
Closes #220

### CODE REVIEW

**Comment by armab** [comment]
Will wait for new Ansible linting fixes to land: https://github.com/StackStorm/ansible-st2/pull/221 to unblock CircleCI build.

**Comment by armab** [comment]
`ansible-st2` had a lot of breaking changes before including role renames. A quick example: https://github.com/StackStorm/ansible-st2/releases/tag/v0.6.0

I think at minimum, the usual - we address this via major version change + changelog in releases: https://github.com/StackStorm/ansible-st2/releases/tag/untagged-8d65387f60686695b748

At maximum, - can do a blog post sometime later about `v1.0.0` release.

**Comment by armab** [comment]
One more thing remembered from your message is that I need to update `st2docs`: https://docs.stackstorm.com/install/ansible.html#bwc

**Comment by LindsayHill** [comment]
#221 has now been merged - you should be able to update this branch to get those linting changes to take effect, so CircleCI checks go ✅

**Pull request merged**
