### PR TITLE
[#246]  Drop Ubuntu Trusty support

### LINKED ISSUE #246: Drop Ubuntu 14 support since st2 v3.1
Per https://docs.stackstorm.com/roadmap.html#roadmap StackStorm v3.1 deprecates Ubuntu14 support as it reached end of life.

Remove Ubuntu14 support from plays.

### PR DESCRIPTION
**Pull request by amanda11**
Closes #246

Remove `ubuntu trusty` which was dropped since st2 `v3.2.1`

### CODE REVIEW

**Comment by armab** [comment]
I just updated PR description to close the #246 once we merge this.
@amanda11 this might be useful: https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by amanda11** [comment]
> I just updated PR description to close the #246 once we merge this.
> @amanda11 this might be useful: https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

Didn't know that - brilliant - will use that from now on. Thanks for pointer.

**Comment by amanda11** [comment]
Any changes requested? Approved but awaiting merging by someone with write access.

**Comment by armab** [comment]
I think this PR was merged. Good work here!

**Pull request merged**
